version: '3.4'

services:
  mysqldb:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'rootpassword'
    ports:
      - 3306:3306
    volumes:
      - D:\Volums\MySqlData:/var/lib/mysql

  mywallet:
    image: ${DOCKER_REGISTRY-}mywallet
    build:
      context: .
      dockerfile: MyWallet/Dockerfile
    environment:
      MYWALLET_DB_USER_PASSWORD: 'rootpassword'
      MYWALLET_DB_USER: 'root'
      ASPNETCORE_URLS: 'http://+:5000'
    ports:
      - 8080:5000